package cn.com.eship.models;

public class Aajiqiyexinxi {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESHIP_LIQ.AAJIQIYEXINXI.ZZJGDM
     *
     * @mbggenerated
     */
    private String zzjgdm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESHIP_LIQ.AAJIQIYEXINXI.QYMC
     *
     * @mbggenerated
     */
    private String qymc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ESHIP_LIQ.AAJIQIYEXINXI.QYZCH
     *
     * @mbggenerated
     */
    private String qyzch;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESHIP_LIQ.AAJIQIYEXINXI.ZZJGDM
     *
     * @return the value of ESHIP_LIQ.AAJIQIYEXINXI.ZZJGDM
     *
     * @mbggenerated
     */
    public String getZzjgdm() {
        return zzjgdm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESHIP_LIQ.AAJIQIYEXINXI.ZZJGDM
     *
     * @param zzjgdm the value for ESHIP_LIQ.AAJIQIYEXINXI.ZZJGDM
     *
     * @mbggenerated
     */
    public void setZzjgdm(String zzjgdm) {
        this.zzjgdm = zzjgdm == null ? null : zzjgdm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESHIP_LIQ.AAJIQIYEXINXI.QYMC
     *
     * @return the value of ESHIP_LIQ.AAJIQIYEXINXI.QYMC
     *
     * @mbggenerated
     */
    public String getQymc() {
        return qymc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESHIP_LIQ.AAJIQIYEXINXI.QYMC
     *
     * @param qymc the value for ESHIP_LIQ.AAJIQIYEXINXI.QYMC
     *
     * @mbggenerated
     */
    public void setQymc(String qymc) {
        this.qymc = qymc == null ? null : qymc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ESHIP_LIQ.AAJIQIYEXINXI.QYZCH
     *
     * @return the value of ESHIP_LIQ.AAJIQIYEXINXI.QYZCH
     *
     * @mbggenerated
     */
    public String getQyzch() {
        return qyzch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ESHIP_LIQ.AAJIQIYEXINXI.QYZCH
     *
     * @param qyzch the value for ESHIP_LIQ.AAJIQIYEXINXI.QYZCH
     *
     * @mbggenerated
     */
    public void setQyzch(String qyzch) {
        this.qyzch = qyzch == null ? null : qyzch.trim();
    }
}