package cn.com.eship.models;

import java.math.BigDecimal;
import java.util.Date;

public class ItfDclIoDecl {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_NO
     *
     * @mbggenerated
     */
    private String declNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_MODE_CODE
     *
     * @mbggenerated
     */
    private String tradeModeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONTRACT_NO
     *
     * @mbggenerated
     */
    private String contractNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.MARK_NO
     *
     * @mbggenerated
     */
    private String markNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_COUNTRY_CODE
     *
     * @mbggenerated
     */
    private String tradeCountryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_CTRY_CODE
     *
     * @mbggenerated
     */
    private String despCtryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MODE_CODE
     *
     * @mbggenerated
     */
    private String transModeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONVYNCE_NAME
     *
     * @mbggenerated
     */
    private String convynceName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MEAN_NO
     *
     * @mbggenerated
     */
    private String transMeanNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_PORT_CODE
     *
     * @mbggenerated
     */
    private String despPortCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_STOP_CODE
     *
     * @mbggenerated
     */
    private String portStopCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENTY_PORT_CODE
     *
     * @mbggenerated
     */
    private String entyPortCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.GDS_ARVL_DATE
     *
     * @mbggenerated
     */
    private Date gdsArvlDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CMPL_DSCHRG_DT
     *
     * @mbggenerated
     */
    private Date cmplDschrgDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.GOODS_PLACE
     *
     * @mbggenerated
     */
    private String goodsPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DEST_CODE
     *
     * @mbggenerated
     */
    private String destCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.COUNTER_CLAIM
     *
     * @mbggenerated
     */
    private Date counterClaim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.BILL_LAD_NO
     *
     * @mbggenerated
     */
    private String billLadNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DELIVERY_ORDER
     *
     * @mbggenerated
     */
    private String deliveryOrder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.INSP_ORG_CODE
     *
     * @mbggenerated
     */
    private String inspOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.EXC_INSP_DEPT_CODE
     *
     * @mbggenerated
     */
    private String excInspDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CUSTM
     *
     * @mbggenerated
     */
    private String declCustm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_DECL_FLAG
     *
     * @mbggenerated
     */
    private String specDeclFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_ORG_CODE
     *
     * @mbggenerated
     */
    private String purpOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_DECL_NO
     *
     * @mbggenerated
     */
    private String correlationDeclNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_REASON_FLAG
     *
     * @mbggenerated
     */
    private String correlationReasonFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPECL_INSP_QURA_RE
     *
     * @mbggenerated
     */
    private String speclInspQuraRe;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_CODE
     *
     * @mbggenerated
     */
    private String appCertCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_ORI
     *
     * @mbggenerated
     */
    private String applOri;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_COPY_QUAN
     *
     * @mbggenerated
     */
    private String applCopyQuan;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CUSTM_REG_NO
     *
     * @mbggenerated
     */
    private String custmRegNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSN_CERT_NO
     *
     * @mbggenerated
     */
    private String declPersnCertNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSON_NAME
     *
     * @mbggenerated
     */
    private String declPersonName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NAME
     *
     * @mbggenerated
     */
    private String declRegName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONTACTPERSON
     *
     * @mbggenerated
     */
    private String contactperson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_TEL
     *
     * @mbggenerated
     */
    private String contTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CODE
     *
     * @mbggenerated
     */
    private String consigneeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CNAME
     *
     * @mbggenerated
     */
    private String consigneeCname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ENAME
     *
     * @mbggenerated
     */
    private String consigneeEname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CNAME
     *
     * @mbggenerated
     */
    private String consignorCname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ADDR
     *
     * @mbggenerated
     */
    private String consignorAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CODE
     *
     * @mbggenerated
     */
    private String declCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_DATE
     *
     * @mbggenerated
     */
    private Date declDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_GET_NO
     *
     * @mbggenerated
     */
    private String declGetNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_PASS_FLAG
     *
     * @mbggenerated
     */
    private String specPassFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_DATE
     *
     * @mbggenerated
     */
    private Date despDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ARRIV_PORT_CODE
     *
     * @mbggenerated
     */
    private String arrivPortCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ADDR
     *
     * @mbggenerated
     */
    private String consigneeAddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CODE
     *
     * @mbggenerated
     */
    private String consignorCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ATTA_COLLECT_NAME
     *
     * @mbggenerated
     */
    private String attaCollectName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_LIST_GOOD
     *
     * @mbggenerated
     */
    private String isListGood;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_CONT
     *
     * @mbggenerated
     */
    private String isCont;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_FLAG
     *
     * @mbggenerated
     */
    private String ffjFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_STATUS
     *
     * @mbggenerated
     */
    private String ffjStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.RESEND_NUM
     *
     * @mbggenerated
     */
    private String resendNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_DRAW
     *
     * @mbggenerated
     */
    private String isDraw;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_US
     *
     * @mbggenerated
     */
    private BigDecimal totalValUs;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_CN
     *
     * @mbggenerated
     */
    private BigDecimal totalValCn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_CANCEL_FLAG
     *
     * @mbggenerated
     */
    private String contCancelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FEE_HANDLE_STATE
     *
     * @mbggenerated
     */
    private String feeHandleState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.RELS_STATE
     *
     * @mbggenerated
     */
    private String relsState;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FLG_PORT_INLAND
     *
     * @mbggenerated
     */
    private String flgPortInland;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENABLE_TRANS_FLAG
     *
     * @mbggenerated
     */
    private String enableTransFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FALG_ARCHIVE
     *
     * @mbggenerated
     */
    private String falgArchive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_CODE
     *
     * @mbggenerated
     */
    private String situationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_LEVEL
     *
     * @mbggenerated
     */
    private String situationLevel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_STATUS
     *
     * @mbggenerated
     */
    private String processStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_CODE
     *
     * @mbggenerated
     */
    private String operCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_TIME
     *
     * @mbggenerated
     */
    private Date operTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_NAME
     *
     * @mbggenerated
     */
    private String appCertName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NO
     *
     * @mbggenerated
     */
    private String declRegNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_DECL_NO
     *
     * @mbggenerated
     */
    private String entDeclNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_LINK
     *
     * @mbggenerated
     */
    private String processLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ORG_CODE
     *
     * @mbggenerated
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CERT_CANCEL_FLAG
     *
     * @mbggenerated
     */
    private String certCancelFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ENAME
     *
     * @mbggenerated
     */
    private String consignorEname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ARCHIVE_TIME
     *
     * @mbggenerated
     */
    private Date archiveTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_FLAG
     *
     * @mbggenerated
     */
    private String transFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_BATCH
     *
     * @mbggenerated
     */
    private String transBatch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_MOVE
     *
     * @mbggenerated
     */
    private String isMove;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPLIT_BILL_LAD_NO
     *
     * @mbggenerated
     */
    private String splitBillLadNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_WORK_NO
     *
     * @mbggenerated
     */
    private String declWorkNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.READ_STATUS
     *
     * @mbggenerated
     */
    private String readStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.WRITE_USEC
     *
     * @mbggenerated
     */
    private String writeUsec;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_UUID
     *
     * @mbggenerated
     */
    private String entUuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_DEPT_CODE
     *
     * @mbggenerated
     */
    private String portDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_DEPT_CODE
     *
     * @mbggenerated
     */
    private String purpDeptCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_ORG_CODE
     *
     * @mbggenerated
     */
    private String portOrgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_TYPE
     *
     * @mbggenerated
     */
    private String declType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ECIQ_GDATA.ITF_DCL_IO_DECL.VSA_ORG_CODE
     *
     * @mbggenerated
     */
    private String vsaOrgCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_NO
     *
     * @mbggenerated
     */
    public String getDeclNo() {
        return declNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_NO
     *
     * @param declNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_NO
     *
     * @mbggenerated
     */
    public void setDeclNo(String declNo) {
        this.declNo = declNo == null ? null : declNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_MODE_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_MODE_CODE
     *
     * @mbggenerated
     */
    public String getTradeModeCode() {
        return tradeModeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_MODE_CODE
     *
     * @param tradeModeCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_MODE_CODE
     *
     * @mbggenerated
     */
    public void setTradeModeCode(String tradeModeCode) {
        this.tradeModeCode = tradeModeCode == null ? null : tradeModeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONTRACT_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONTRACT_NO
     *
     * @mbggenerated
     */
    public String getContractNo() {
        return contractNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONTRACT_NO
     *
     * @param contractNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONTRACT_NO
     *
     * @mbggenerated
     */
    public void setContractNo(String contractNo) {
        this.contractNo = contractNo == null ? null : contractNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.MARK_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.MARK_NO
     *
     * @mbggenerated
     */
    public String getMarkNo() {
        return markNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.MARK_NO
     *
     * @param markNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.MARK_NO
     *
     * @mbggenerated
     */
    public void setMarkNo(String markNo) {
        this.markNo = markNo == null ? null : markNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_COUNTRY_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_COUNTRY_CODE
     *
     * @mbggenerated
     */
    public String getTradeCountryCode() {
        return tradeCountryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_COUNTRY_CODE
     *
     * @param tradeCountryCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.TRADE_COUNTRY_CODE
     *
     * @mbggenerated
     */
    public void setTradeCountryCode(String tradeCountryCode) {
        this.tradeCountryCode = tradeCountryCode == null ? null : tradeCountryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_CTRY_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_CTRY_CODE
     *
     * @mbggenerated
     */
    public String getDespCtryCode() {
        return despCtryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_CTRY_CODE
     *
     * @param despCtryCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_CTRY_CODE
     *
     * @mbggenerated
     */
    public void setDespCtryCode(String despCtryCode) {
        this.despCtryCode = despCtryCode == null ? null : despCtryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MODE_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MODE_CODE
     *
     * @mbggenerated
     */
    public String getTransModeCode() {
        return transModeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MODE_CODE
     *
     * @param transModeCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MODE_CODE
     *
     * @mbggenerated
     */
    public void setTransModeCode(String transModeCode) {
        this.transModeCode = transModeCode == null ? null : transModeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONVYNCE_NAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONVYNCE_NAME
     *
     * @mbggenerated
     */
    public String getConvynceName() {
        return convynceName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONVYNCE_NAME
     *
     * @param convynceName the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONVYNCE_NAME
     *
     * @mbggenerated
     */
    public void setConvynceName(String convynceName) {
        this.convynceName = convynceName == null ? null : convynceName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MEAN_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MEAN_NO
     *
     * @mbggenerated
     */
    public String getTransMeanNo() {
        return transMeanNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MEAN_NO
     *
     * @param transMeanNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_MEAN_NO
     *
     * @mbggenerated
     */
    public void setTransMeanNo(String transMeanNo) {
        this.transMeanNo = transMeanNo == null ? null : transMeanNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_PORT_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_PORT_CODE
     *
     * @mbggenerated
     */
    public String getDespPortCode() {
        return despPortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_PORT_CODE
     *
     * @param despPortCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_PORT_CODE
     *
     * @mbggenerated
     */
    public void setDespPortCode(String despPortCode) {
        this.despPortCode = despPortCode == null ? null : despPortCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_STOP_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_STOP_CODE
     *
     * @mbggenerated
     */
    public String getPortStopCode() {
        return portStopCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_STOP_CODE
     *
     * @param portStopCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_STOP_CODE
     *
     * @mbggenerated
     */
    public void setPortStopCode(String portStopCode) {
        this.portStopCode = portStopCode == null ? null : portStopCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENTY_PORT_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.ENTY_PORT_CODE
     *
     * @mbggenerated
     */
    public String getEntyPortCode() {
        return entyPortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENTY_PORT_CODE
     *
     * @param entyPortCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.ENTY_PORT_CODE
     *
     * @mbggenerated
     */
    public void setEntyPortCode(String entyPortCode) {
        this.entyPortCode = entyPortCode == null ? null : entyPortCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.GDS_ARVL_DATE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.GDS_ARVL_DATE
     *
     * @mbggenerated
     */
    public Date getGdsArvlDate() {
        return gdsArvlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.GDS_ARVL_DATE
     *
     * @param gdsArvlDate the value for ECIQ_GDATA.ITF_DCL_IO_DECL.GDS_ARVL_DATE
     *
     * @mbggenerated
     */
    public void setGdsArvlDate(Date gdsArvlDate) {
        this.gdsArvlDate = gdsArvlDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CMPL_DSCHRG_DT
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CMPL_DSCHRG_DT
     *
     * @mbggenerated
     */
    public Date getCmplDschrgDt() {
        return cmplDschrgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CMPL_DSCHRG_DT
     *
     * @param cmplDschrgDt the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CMPL_DSCHRG_DT
     *
     * @mbggenerated
     */
    public void setCmplDschrgDt(Date cmplDschrgDt) {
        this.cmplDschrgDt = cmplDschrgDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.GOODS_PLACE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.GOODS_PLACE
     *
     * @mbggenerated
     */
    public String getGoodsPlace() {
        return goodsPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.GOODS_PLACE
     *
     * @param goodsPlace the value for ECIQ_GDATA.ITF_DCL_IO_DECL.GOODS_PLACE
     *
     * @mbggenerated
     */
    public void setGoodsPlace(String goodsPlace) {
        this.goodsPlace = goodsPlace == null ? null : goodsPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DEST_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DEST_CODE
     *
     * @mbggenerated
     */
    public String getDestCode() {
        return destCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DEST_CODE
     *
     * @param destCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DEST_CODE
     *
     * @mbggenerated
     */
    public void setDestCode(String destCode) {
        this.destCode = destCode == null ? null : destCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.COUNTER_CLAIM
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.COUNTER_CLAIM
     *
     * @mbggenerated
     */
    public Date getCounterClaim() {
        return counterClaim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.COUNTER_CLAIM
     *
     * @param counterClaim the value for ECIQ_GDATA.ITF_DCL_IO_DECL.COUNTER_CLAIM
     *
     * @mbggenerated
     */
    public void setCounterClaim(Date counterClaim) {
        this.counterClaim = counterClaim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.BILL_LAD_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.BILL_LAD_NO
     *
     * @mbggenerated
     */
    public String getBillLadNo() {
        return billLadNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.BILL_LAD_NO
     *
     * @param billLadNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.BILL_LAD_NO
     *
     * @mbggenerated
     */
    public void setBillLadNo(String billLadNo) {
        this.billLadNo = billLadNo == null ? null : billLadNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DELIVERY_ORDER
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DELIVERY_ORDER
     *
     * @mbggenerated
     */
    public String getDeliveryOrder() {
        return deliveryOrder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DELIVERY_ORDER
     *
     * @param deliveryOrder the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DELIVERY_ORDER
     *
     * @mbggenerated
     */
    public void setDeliveryOrder(String deliveryOrder) {
        this.deliveryOrder = deliveryOrder == null ? null : deliveryOrder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.INSP_ORG_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.INSP_ORG_CODE
     *
     * @mbggenerated
     */
    public String getInspOrgCode() {
        return inspOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.INSP_ORG_CODE
     *
     * @param inspOrgCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.INSP_ORG_CODE
     *
     * @mbggenerated
     */
    public void setInspOrgCode(String inspOrgCode) {
        this.inspOrgCode = inspOrgCode == null ? null : inspOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.EXC_INSP_DEPT_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.EXC_INSP_DEPT_CODE
     *
     * @mbggenerated
     */
    public String getExcInspDeptCode() {
        return excInspDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.EXC_INSP_DEPT_CODE
     *
     * @param excInspDeptCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.EXC_INSP_DEPT_CODE
     *
     * @mbggenerated
     */
    public void setExcInspDeptCode(String excInspDeptCode) {
        this.excInspDeptCode = excInspDeptCode == null ? null : excInspDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CUSTM
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CUSTM
     *
     * @mbggenerated
     */
    public String getDeclCustm() {
        return declCustm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CUSTM
     *
     * @param declCustm the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CUSTM
     *
     * @mbggenerated
     */
    public void setDeclCustm(String declCustm) {
        this.declCustm = declCustm == null ? null : declCustm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_DECL_FLAG
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_DECL_FLAG
     *
     * @mbggenerated
     */
    public String getSpecDeclFlag() {
        return specDeclFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_DECL_FLAG
     *
     * @param specDeclFlag the value for ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_DECL_FLAG
     *
     * @mbggenerated
     */
    public void setSpecDeclFlag(String specDeclFlag) {
        this.specDeclFlag = specDeclFlag == null ? null : specDeclFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_ORG_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_ORG_CODE
     *
     * @mbggenerated
     */
    public String getPurpOrgCode() {
        return purpOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_ORG_CODE
     *
     * @param purpOrgCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_ORG_CODE
     *
     * @mbggenerated
     */
    public void setPurpOrgCode(String purpOrgCode) {
        this.purpOrgCode = purpOrgCode == null ? null : purpOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_DECL_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_DECL_NO
     *
     * @mbggenerated
     */
    public String getCorrelationDeclNo() {
        return correlationDeclNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_DECL_NO
     *
     * @param correlationDeclNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_DECL_NO
     *
     * @mbggenerated
     */
    public void setCorrelationDeclNo(String correlationDeclNo) {
        this.correlationDeclNo = correlationDeclNo == null ? null : correlationDeclNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_REASON_FLAG
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_REASON_FLAG
     *
     * @mbggenerated
     */
    public String getCorrelationReasonFlag() {
        return correlationReasonFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_REASON_FLAG
     *
     * @param correlationReasonFlag the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CORRELATION_REASON_FLAG
     *
     * @mbggenerated
     */
    public void setCorrelationReasonFlag(String correlationReasonFlag) {
        this.correlationReasonFlag = correlationReasonFlag == null ? null : correlationReasonFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPECL_INSP_QURA_RE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.SPECL_INSP_QURA_RE
     *
     * @mbggenerated
     */
    public String getSpeclInspQuraRe() {
        return speclInspQuraRe;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPECL_INSP_QURA_RE
     *
     * @param speclInspQuraRe the value for ECIQ_GDATA.ITF_DCL_IO_DECL.SPECL_INSP_QURA_RE
     *
     * @mbggenerated
     */
    public void setSpeclInspQuraRe(String speclInspQuraRe) {
        this.speclInspQuraRe = speclInspQuraRe == null ? null : speclInspQuraRe.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_CODE
     *
     * @mbggenerated
     */
    public String getAppCertCode() {
        return appCertCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_CODE
     *
     * @param appCertCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_CODE
     *
     * @mbggenerated
     */
    public void setAppCertCode(String appCertCode) {
        this.appCertCode = appCertCode == null ? null : appCertCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_ORI
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_ORI
     *
     * @mbggenerated
     */
    public String getApplOri() {
        return applOri;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_ORI
     *
     * @param applOri the value for ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_ORI
     *
     * @mbggenerated
     */
    public void setApplOri(String applOri) {
        this.applOri = applOri == null ? null : applOri.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_COPY_QUAN
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_COPY_QUAN
     *
     * @mbggenerated
     */
    public String getApplCopyQuan() {
        return applCopyQuan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_COPY_QUAN
     *
     * @param applCopyQuan the value for ECIQ_GDATA.ITF_DCL_IO_DECL.APPL_COPY_QUAN
     *
     * @mbggenerated
     */
    public void setApplCopyQuan(String applCopyQuan) {
        this.applCopyQuan = applCopyQuan == null ? null : applCopyQuan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CUSTM_REG_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CUSTM_REG_NO
     *
     * @mbggenerated
     */
    public String getCustmRegNo() {
        return custmRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CUSTM_REG_NO
     *
     * @param custmRegNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CUSTM_REG_NO
     *
     * @mbggenerated
     */
    public void setCustmRegNo(String custmRegNo) {
        this.custmRegNo = custmRegNo == null ? null : custmRegNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSN_CERT_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSN_CERT_NO
     *
     * @mbggenerated
     */
    public String getDeclPersnCertNo() {
        return declPersnCertNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSN_CERT_NO
     *
     * @param declPersnCertNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSN_CERT_NO
     *
     * @mbggenerated
     */
    public void setDeclPersnCertNo(String declPersnCertNo) {
        this.declPersnCertNo = declPersnCertNo == null ? null : declPersnCertNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSON_NAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSON_NAME
     *
     * @mbggenerated
     */
    public String getDeclPersonName() {
        return declPersonName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSON_NAME
     *
     * @param declPersonName the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_PERSON_NAME
     *
     * @mbggenerated
     */
    public void setDeclPersonName(String declPersonName) {
        this.declPersonName = declPersonName == null ? null : declPersonName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NAME
     *
     * @mbggenerated
     */
    public String getDeclRegName() {
        return declRegName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NAME
     *
     * @param declRegName the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NAME
     *
     * @mbggenerated
     */
    public void setDeclRegName(String declRegName) {
        this.declRegName = declRegName == null ? null : declRegName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONTACTPERSON
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONTACTPERSON
     *
     * @mbggenerated
     */
    public String getContactperson() {
        return contactperson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONTACTPERSON
     *
     * @param contactperson the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONTACTPERSON
     *
     * @mbggenerated
     */
    public void setContactperson(String contactperson) {
        this.contactperson = contactperson == null ? null : contactperson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_TEL
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_TEL
     *
     * @mbggenerated
     */
    public String getContTel() {
        return contTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_TEL
     *
     * @param contTel the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_TEL
     *
     * @mbggenerated
     */
    public void setContTel(String contTel) {
        this.contTel = contTel == null ? null : contTel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CODE
     *
     * @mbggenerated
     */
    public String getConsigneeCode() {
        return consigneeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CODE
     *
     * @param consigneeCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CODE
     *
     * @mbggenerated
     */
    public void setConsigneeCode(String consigneeCode) {
        this.consigneeCode = consigneeCode == null ? null : consigneeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CNAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CNAME
     *
     * @mbggenerated
     */
    public String getConsigneeCname() {
        return consigneeCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CNAME
     *
     * @param consigneeCname the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_CNAME
     *
     * @mbggenerated
     */
    public void setConsigneeCname(String consigneeCname) {
        this.consigneeCname = consigneeCname == null ? null : consigneeCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ENAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ENAME
     *
     * @mbggenerated
     */
    public String getConsigneeEname() {
        return consigneeEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ENAME
     *
     * @param consigneeEname the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ENAME
     *
     * @mbggenerated
     */
    public void setConsigneeEname(String consigneeEname) {
        this.consigneeEname = consigneeEname == null ? null : consigneeEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CNAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CNAME
     *
     * @mbggenerated
     */
    public String getConsignorCname() {
        return consignorCname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CNAME
     *
     * @param consignorCname the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CNAME
     *
     * @mbggenerated
     */
    public void setConsignorCname(String consignorCname) {
        this.consignorCname = consignorCname == null ? null : consignorCname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ADDR
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ADDR
     *
     * @mbggenerated
     */
    public String getConsignorAddr() {
        return consignorAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ADDR
     *
     * @param consignorAddr the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ADDR
     *
     * @mbggenerated
     */
    public void setConsignorAddr(String consignorAddr) {
        this.consignorAddr = consignorAddr == null ? null : consignorAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CODE
     *
     * @mbggenerated
     */
    public String getDeclCode() {
        return declCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CODE
     *
     * @param declCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_CODE
     *
     * @mbggenerated
     */
    public void setDeclCode(String declCode) {
        this.declCode = declCode == null ? null : declCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_DATE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_DATE
     *
     * @mbggenerated
     */
    public Date getDeclDate() {
        return declDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_DATE
     *
     * @param declDate the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_DATE
     *
     * @mbggenerated
     */
    public void setDeclDate(Date declDate) {
        this.declDate = declDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_GET_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_GET_NO
     *
     * @mbggenerated
     */
    public String getDeclGetNo() {
        return declGetNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_GET_NO
     *
     * @param declGetNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_GET_NO
     *
     * @mbggenerated
     */
    public void setDeclGetNo(String declGetNo) {
        this.declGetNo = declGetNo == null ? null : declGetNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_PASS_FLAG
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_PASS_FLAG
     *
     * @mbggenerated
     */
    public String getSpecPassFlag() {
        return specPassFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_PASS_FLAG
     *
     * @param specPassFlag the value for ECIQ_GDATA.ITF_DCL_IO_DECL.SPEC_PASS_FLAG
     *
     * @mbggenerated
     */
    public void setSpecPassFlag(String specPassFlag) {
        this.specPassFlag = specPassFlag == null ? null : specPassFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_DATE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_DATE
     *
     * @mbggenerated
     */
    public Date getDespDate() {
        return despDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_DATE
     *
     * @param despDate the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DESP_DATE
     *
     * @mbggenerated
     */
    public void setDespDate(Date despDate) {
        this.despDate = despDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ARRIV_PORT_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.ARRIV_PORT_CODE
     *
     * @mbggenerated
     */
    public String getArrivPortCode() {
        return arrivPortCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ARRIV_PORT_CODE
     *
     * @param arrivPortCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.ARRIV_PORT_CODE
     *
     * @mbggenerated
     */
    public void setArrivPortCode(String arrivPortCode) {
        this.arrivPortCode = arrivPortCode == null ? null : arrivPortCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ADDR
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ADDR
     *
     * @mbggenerated
     */
    public String getConsigneeAddr() {
        return consigneeAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ADDR
     *
     * @param consigneeAddr the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNEE_ADDR
     *
     * @mbggenerated
     */
    public void setConsigneeAddr(String consigneeAddr) {
        this.consigneeAddr = consigneeAddr == null ? null : consigneeAddr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CODE
     *
     * @mbggenerated
     */
    public String getConsignorCode() {
        return consignorCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CODE
     *
     * @param consignorCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_CODE
     *
     * @mbggenerated
     */
    public void setConsignorCode(String consignorCode) {
        this.consignorCode = consignorCode == null ? null : consignorCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ATTA_COLLECT_NAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.ATTA_COLLECT_NAME
     *
     * @mbggenerated
     */
    public String getAttaCollectName() {
        return attaCollectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ATTA_COLLECT_NAME
     *
     * @param attaCollectName the value for ECIQ_GDATA.ITF_DCL_IO_DECL.ATTA_COLLECT_NAME
     *
     * @mbggenerated
     */
    public void setAttaCollectName(String attaCollectName) {
        this.attaCollectName = attaCollectName == null ? null : attaCollectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_LIST_GOOD
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.IS_LIST_GOOD
     *
     * @mbggenerated
     */
    public String getIsListGood() {
        return isListGood;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_LIST_GOOD
     *
     * @param isListGood the value for ECIQ_GDATA.ITF_DCL_IO_DECL.IS_LIST_GOOD
     *
     * @mbggenerated
     */
    public void setIsListGood(String isListGood) {
        this.isListGood = isListGood == null ? null : isListGood.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_CONT
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.IS_CONT
     *
     * @mbggenerated
     */
    public String getIsCont() {
        return isCont;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_CONT
     *
     * @param isCont the value for ECIQ_GDATA.ITF_DCL_IO_DECL.IS_CONT
     *
     * @mbggenerated
     */
    public void setIsCont(String isCont) {
        this.isCont = isCont == null ? null : isCont.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_FLAG
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_FLAG
     *
     * @mbggenerated
     */
    public String getFfjFlag() {
        return ffjFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_FLAG
     *
     * @param ffjFlag the value for ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_FLAG
     *
     * @mbggenerated
     */
    public void setFfjFlag(String ffjFlag) {
        this.ffjFlag = ffjFlag == null ? null : ffjFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_STATUS
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_STATUS
     *
     * @mbggenerated
     */
    public String getFfjStatus() {
        return ffjStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_STATUS
     *
     * @param ffjStatus the value for ECIQ_GDATA.ITF_DCL_IO_DECL.FFJ_STATUS
     *
     * @mbggenerated
     */
    public void setFfjStatus(String ffjStatus) {
        this.ffjStatus = ffjStatus == null ? null : ffjStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.RESEND_NUM
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.RESEND_NUM
     *
     * @mbggenerated
     */
    public String getResendNum() {
        return resendNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.RESEND_NUM
     *
     * @param resendNum the value for ECIQ_GDATA.ITF_DCL_IO_DECL.RESEND_NUM
     *
     * @mbggenerated
     */
    public void setResendNum(String resendNum) {
        this.resendNum = resendNum == null ? null : resendNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_DRAW
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.IS_DRAW
     *
     * @mbggenerated
     */
    public String getIsDraw() {
        return isDraw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_DRAW
     *
     * @param isDraw the value for ECIQ_GDATA.ITF_DCL_IO_DECL.IS_DRAW
     *
     * @mbggenerated
     */
    public void setIsDraw(String isDraw) {
        this.isDraw = isDraw == null ? null : isDraw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_US
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_US
     *
     * @mbggenerated
     */
    public BigDecimal getTotalValUs() {
        return totalValUs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_US
     *
     * @param totalValUs the value for ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_US
     *
     * @mbggenerated
     */
    public void setTotalValUs(BigDecimal totalValUs) {
        this.totalValUs = totalValUs;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_CN
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_CN
     *
     * @mbggenerated
     */
    public BigDecimal getTotalValCn() {
        return totalValCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_CN
     *
     * @param totalValCn the value for ECIQ_GDATA.ITF_DCL_IO_DECL.TOTAL_VAL_CN
     *
     * @mbggenerated
     */
    public void setTotalValCn(BigDecimal totalValCn) {
        this.totalValCn = totalValCn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_CANCEL_FLAG
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_CANCEL_FLAG
     *
     * @mbggenerated
     */
    public String getContCancelFlag() {
        return contCancelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_CANCEL_FLAG
     *
     * @param contCancelFlag the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONT_CANCEL_FLAG
     *
     * @mbggenerated
     */
    public void setContCancelFlag(String contCancelFlag) {
        this.contCancelFlag = contCancelFlag == null ? null : contCancelFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FEE_HANDLE_STATE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.FEE_HANDLE_STATE
     *
     * @mbggenerated
     */
    public String getFeeHandleState() {
        return feeHandleState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FEE_HANDLE_STATE
     *
     * @param feeHandleState the value for ECIQ_GDATA.ITF_DCL_IO_DECL.FEE_HANDLE_STATE
     *
     * @mbggenerated
     */
    public void setFeeHandleState(String feeHandleState) {
        this.feeHandleState = feeHandleState == null ? null : feeHandleState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.RELS_STATE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.RELS_STATE
     *
     * @mbggenerated
     */
    public String getRelsState() {
        return relsState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.RELS_STATE
     *
     * @param relsState the value for ECIQ_GDATA.ITF_DCL_IO_DECL.RELS_STATE
     *
     * @mbggenerated
     */
    public void setRelsState(String relsState) {
        this.relsState = relsState == null ? null : relsState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FLG_PORT_INLAND
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.FLG_PORT_INLAND
     *
     * @mbggenerated
     */
    public String getFlgPortInland() {
        return flgPortInland;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FLG_PORT_INLAND
     *
     * @param flgPortInland the value for ECIQ_GDATA.ITF_DCL_IO_DECL.FLG_PORT_INLAND
     *
     * @mbggenerated
     */
    public void setFlgPortInland(String flgPortInland) {
        this.flgPortInland = flgPortInland == null ? null : flgPortInland.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENABLE_TRANS_FLAG
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.ENABLE_TRANS_FLAG
     *
     * @mbggenerated
     */
    public String getEnableTransFlag() {
        return enableTransFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENABLE_TRANS_FLAG
     *
     * @param enableTransFlag the value for ECIQ_GDATA.ITF_DCL_IO_DECL.ENABLE_TRANS_FLAG
     *
     * @mbggenerated
     */
    public void setEnableTransFlag(String enableTransFlag) {
        this.enableTransFlag = enableTransFlag == null ? null : enableTransFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FALG_ARCHIVE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.FALG_ARCHIVE
     *
     * @mbggenerated
     */
    public String getFalgArchive() {
        return falgArchive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.FALG_ARCHIVE
     *
     * @param falgArchive the value for ECIQ_GDATA.ITF_DCL_IO_DECL.FALG_ARCHIVE
     *
     * @mbggenerated
     */
    public void setFalgArchive(String falgArchive) {
        this.falgArchive = falgArchive == null ? null : falgArchive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_CODE
     *
     * @mbggenerated
     */
    public String getSituationCode() {
        return situationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_CODE
     *
     * @param situationCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_CODE
     *
     * @mbggenerated
     */
    public void setSituationCode(String situationCode) {
        this.situationCode = situationCode == null ? null : situationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_LEVEL
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_LEVEL
     *
     * @mbggenerated
     */
    public String getSituationLevel() {
        return situationLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_LEVEL
     *
     * @param situationLevel the value for ECIQ_GDATA.ITF_DCL_IO_DECL.SITUATION_LEVEL
     *
     * @mbggenerated
     */
    public void setSituationLevel(String situationLevel) {
        this.situationLevel = situationLevel == null ? null : situationLevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_STATUS
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_STATUS
     *
     * @mbggenerated
     */
    public String getProcessStatus() {
        return processStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_STATUS
     *
     * @param processStatus the value for ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_STATUS
     *
     * @mbggenerated
     */
    public void setProcessStatus(String processStatus) {
        this.processStatus = processStatus == null ? null : processStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_CODE
     *
     * @mbggenerated
     */
    public String getOperCode() {
        return operCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_CODE
     *
     * @param operCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_CODE
     *
     * @mbggenerated
     */
    public void setOperCode(String operCode) {
        this.operCode = operCode == null ? null : operCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_TIME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_TIME
     *
     * @mbggenerated
     */
    public Date getOperTime() {
        return operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_TIME
     *
     * @param operTime the value for ECIQ_GDATA.ITF_DCL_IO_DECL.OPER_TIME
     *
     * @mbggenerated
     */
    public void setOperTime(Date operTime) {
        this.operTime = operTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_NAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_NAME
     *
     * @mbggenerated
     */
    public String getAppCertName() {
        return appCertName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_NAME
     *
     * @param appCertName the value for ECIQ_GDATA.ITF_DCL_IO_DECL.APP_CERT_NAME
     *
     * @mbggenerated
     */
    public void setAppCertName(String appCertName) {
        this.appCertName = appCertName == null ? null : appCertName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NO
     *
     * @mbggenerated
     */
    public String getDeclRegNo() {
        return declRegNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NO
     *
     * @param declRegNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_REG_NO
     *
     * @mbggenerated
     */
    public void setDeclRegNo(String declRegNo) {
        this.declRegNo = declRegNo == null ? null : declRegNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_DECL_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_DECL_NO
     *
     * @mbggenerated
     */
    public String getEntDeclNo() {
        return entDeclNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_DECL_NO
     *
     * @param entDeclNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_DECL_NO
     *
     * @mbggenerated
     */
    public void setEntDeclNo(String entDeclNo) {
        this.entDeclNo = entDeclNo == null ? null : entDeclNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_LINK
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_LINK
     *
     * @mbggenerated
     */
    public String getProcessLink() {
        return processLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_LINK
     *
     * @param processLink the value for ECIQ_GDATA.ITF_DCL_IO_DECL.PROCESS_LINK
     *
     * @mbggenerated
     */
    public void setProcessLink(String processLink) {
        this.processLink = processLink == null ? null : processLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ORG_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.ORG_CODE
     *
     * @mbggenerated
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ORG_CODE
     *
     * @param orgCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.ORG_CODE
     *
     * @mbggenerated
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CERT_CANCEL_FLAG
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CERT_CANCEL_FLAG
     *
     * @mbggenerated
     */
    public String getCertCancelFlag() {
        return certCancelFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CERT_CANCEL_FLAG
     *
     * @param certCancelFlag the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CERT_CANCEL_FLAG
     *
     * @mbggenerated
     */
    public void setCertCancelFlag(String certCancelFlag) {
        this.certCancelFlag = certCancelFlag == null ? null : certCancelFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ENAME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ENAME
     *
     * @mbggenerated
     */
    public String getConsignorEname() {
        return consignorEname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ENAME
     *
     * @param consignorEname the value for ECIQ_GDATA.ITF_DCL_IO_DECL.CONSIGNOR_ENAME
     *
     * @mbggenerated
     */
    public void setConsignorEname(String consignorEname) {
        this.consignorEname = consignorEname == null ? null : consignorEname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ARCHIVE_TIME
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.ARCHIVE_TIME
     *
     * @mbggenerated
     */
    public Date getArchiveTime() {
        return archiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ARCHIVE_TIME
     *
     * @param archiveTime the value for ECIQ_GDATA.ITF_DCL_IO_DECL.ARCHIVE_TIME
     *
     * @mbggenerated
     */
    public void setArchiveTime(Date archiveTime) {
        this.archiveTime = archiveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_FLAG
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_FLAG
     *
     * @mbggenerated
     */
    public String getTransFlag() {
        return transFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_FLAG
     *
     * @param transFlag the value for ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_FLAG
     *
     * @mbggenerated
     */
    public void setTransFlag(String transFlag) {
        this.transFlag = transFlag == null ? null : transFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_BATCH
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_BATCH
     *
     * @mbggenerated
     */
    public String getTransBatch() {
        return transBatch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_BATCH
     *
     * @param transBatch the value for ECIQ_GDATA.ITF_DCL_IO_DECL.TRANS_BATCH
     *
     * @mbggenerated
     */
    public void setTransBatch(String transBatch) {
        this.transBatch = transBatch == null ? null : transBatch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_MOVE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.IS_MOVE
     *
     * @mbggenerated
     */
    public String getIsMove() {
        return isMove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.IS_MOVE
     *
     * @param isMove the value for ECIQ_GDATA.ITF_DCL_IO_DECL.IS_MOVE
     *
     * @mbggenerated
     */
    public void setIsMove(String isMove) {
        this.isMove = isMove == null ? null : isMove.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPLIT_BILL_LAD_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.SPLIT_BILL_LAD_NO
     *
     * @mbggenerated
     */
    public String getSplitBillLadNo() {
        return splitBillLadNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.SPLIT_BILL_LAD_NO
     *
     * @param splitBillLadNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.SPLIT_BILL_LAD_NO
     *
     * @mbggenerated
     */
    public void setSplitBillLadNo(String splitBillLadNo) {
        this.splitBillLadNo = splitBillLadNo == null ? null : splitBillLadNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_WORK_NO
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_WORK_NO
     *
     * @mbggenerated
     */
    public String getDeclWorkNo() {
        return declWorkNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_WORK_NO
     *
     * @param declWorkNo the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_WORK_NO
     *
     * @mbggenerated
     */
    public void setDeclWorkNo(String declWorkNo) {
        this.declWorkNo = declWorkNo == null ? null : declWorkNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.READ_STATUS
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.READ_STATUS
     *
     * @mbggenerated
     */
    public String getReadStatus() {
        return readStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.READ_STATUS
     *
     * @param readStatus the value for ECIQ_GDATA.ITF_DCL_IO_DECL.READ_STATUS
     *
     * @mbggenerated
     */
    public void setReadStatus(String readStatus) {
        this.readStatus = readStatus == null ? null : readStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.WRITE_USEC
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.WRITE_USEC
     *
     * @mbggenerated
     */
    public String getWriteUsec() {
        return writeUsec;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.WRITE_USEC
     *
     * @param writeUsec the value for ECIQ_GDATA.ITF_DCL_IO_DECL.WRITE_USEC
     *
     * @mbggenerated
     */
    public void setWriteUsec(String writeUsec) {
        this.writeUsec = writeUsec == null ? null : writeUsec.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_UUID
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_UUID
     *
     * @mbggenerated
     */
    public String getEntUuid() {
        return entUuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_UUID
     *
     * @param entUuid the value for ECIQ_GDATA.ITF_DCL_IO_DECL.ENT_UUID
     *
     * @mbggenerated
     */
    public void setEntUuid(String entUuid) {
        this.entUuid = entUuid == null ? null : entUuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_DEPT_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_DEPT_CODE
     *
     * @mbggenerated
     */
    public String getPortDeptCode() {
        return portDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_DEPT_CODE
     *
     * @param portDeptCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_DEPT_CODE
     *
     * @mbggenerated
     */
    public void setPortDeptCode(String portDeptCode) {
        this.portDeptCode = portDeptCode == null ? null : portDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_DEPT_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_DEPT_CODE
     *
     * @mbggenerated
     */
    public String getPurpDeptCode() {
        return purpDeptCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_DEPT_CODE
     *
     * @param purpDeptCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.PURP_DEPT_CODE
     *
     * @mbggenerated
     */
    public void setPurpDeptCode(String purpDeptCode) {
        this.purpDeptCode = purpDeptCode == null ? null : purpDeptCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_ORG_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_ORG_CODE
     *
     * @mbggenerated
     */
    public String getPortOrgCode() {
        return portOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_ORG_CODE
     *
     * @param portOrgCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.PORT_ORG_CODE
     *
     * @mbggenerated
     */
    public void setPortOrgCode(String portOrgCode) {
        this.portOrgCode = portOrgCode == null ? null : portOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_TYPE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_TYPE
     *
     * @mbggenerated
     */
    public String getDeclType() {
        return declType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_TYPE
     *
     * @param declType the value for ECIQ_GDATA.ITF_DCL_IO_DECL.DECL_TYPE
     *
     * @mbggenerated
     */
    public void setDeclType(String declType) {
        this.declType = declType == null ? null : declType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.VSA_ORG_CODE
     *
     * @return the value of ECIQ_GDATA.ITF_DCL_IO_DECL.VSA_ORG_CODE
     *
     * @mbggenerated
     */
    public String getVsaOrgCode() {
        return vsaOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ECIQ_GDATA.ITF_DCL_IO_DECL.VSA_ORG_CODE
     *
     * @param vsaOrgCode the value for ECIQ_GDATA.ITF_DCL_IO_DECL.VSA_ORG_CODE
     *
     * @mbggenerated
     */
    public void setVsaOrgCode(String vsaOrgCode) {
        this.vsaOrgCode = vsaOrgCode == null ? null : vsaOrgCode.trim();
    }
}