package cn.com.eship.repository;

import cn.com.eship.models.Aajiqiyexinxi;

public interface AajiqiyexinxiMapper {

    Aajiqiyexinxi selectByPrimaryKey(String zzjgdm);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESHIP_LIQ.AAJIQIYEXINXI
     *
     * @mbggenerated
     */
    int insert(Aajiqiyexinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESHIP_LIQ.AAJIQIYEXINXI
     *
     * @mbggenerated
     */
    int insertSelective(Aajiqiyexinxi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ESHIP_LIQ.AAJIQIYEXINXI
     *
     * @mbggenerated
     */
}