package cn.com.eship.repository;

import cn.com.eship.models.ItfDclIoDecl;
import org.springframework.stereotype.Repository;

@Repository
public interface ItfDclIoDeclMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_DCL_IO_DECL
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String declNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_DCL_IO_DECL
     *
     * @mbggenerated
     */
    int insert(ItfDclIoDecl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_DCL_IO_DECL
     *
     * @mbggenerated
     */
    int insertSelective(ItfDclIoDecl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_DCL_IO_DECL
     *
     * @mbggenerated
     */
    ItfDclIoDecl selectByPrimaryKey(String declNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_DCL_IO_DECL
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItfDclIoDecl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_DCL_IO_DECL
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItfDclIoDecl record);
}