package cn.com.eship.repository;

import cn.com.eship.models.ItfEntBaseInfo;

import java.util.List;

public interface ItfEntBaseInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_ENT_BASE_INFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String entInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_ENT_BASE_INFO
     *
     * @mbggenerated
     */
    int insert(ItfEntBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_ENT_BASE_INFO
     *
     * @mbggenerated
     */
    int insertSelective(ItfEntBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_ENT_BASE_INFO
     *
     * @mbggenerated
     */
    ItfEntBaseInfo selectByPrimaryKey(String entInfoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_ENT_BASE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ItfEntBaseInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ECIQ_GDATA.ITF_ENT_BASE_INFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ItfEntBaseInfo record);

    List<ItfEntBaseInfo> selectItfEntBaseInfo(String str);

    ItfEntBaseInfo selectItfEntBaseInfoByZzjgdm(String zzjgdm);
}